global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nestjs-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['nestjs-app:3001']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

